version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BookForgeDb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped