create table genre (
    id bigint generated by default as identity,
    description varchar(255) not null,
    name varchar(255) not null unique,
    primary key (id)
);

create table member (
    id bigint generated by default as identity,
    birth_date date not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    email varchar(255) not null unique,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null check (role in ('READER','WRITER','ADMIN')),
    username varchar(255) not null unique,
    primary key (id)
);

create table book (
    id bigint generated by default as identity,
    pages integer not null,
    price integer not null,
    added_at timestamp(6) not null,
    author_id bigint not null,
    genre_id bigint not null,
    likes bigint not null,
    updated_at timestamp(6) not null,
    description varchar(2048) not null,
    isbn varchar(255) not null unique,
    title varchar(255) not null,
    primary key (id)
);

create table user_library (
    book_id bigint not null,
    user_id bigint not null,
    primary key (book_id, user_id)
);

alter table if exists book
    add constraint FK_book_author
    foreign key (author_id) references member(id);

alter table if exists book
    add constraint FK_book_genre
    foreign key (genre_id) references genre(id);

alter table if exists user_library
    add constraint FK_user_library_book
    foreign key (book_id) references book(id);

alter table if exists user_library
    add constraint FK_user_library_user
    foreign key (user_id) references member(id);
